### ISSUE TITLE
Beta / 2018 Edition compatibility complications

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/bare-metal#11]
I was just checking how well my crates would play with the 2018 edition and I was able to work around most quirks except for a few with the most major probably being that it seems to be impossible to share peripherals via the good old `Mutex<RefCell<Option<_>>>` static mechanism due to the inavailability of `const_fn`:

```
error[E0015]: calls in statics are limited to tuple structs and tuple variants
  --> examples/i2c_haldriver_printmagserial.rs:31:62
   |
31 | static MAG3110: Mutex<RefCell<Option<Mag3110<I2c<TWI1>>>>> = Mutex::new(RefCell::new(None));
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: a limited form of compile-time function evaluation is available on a nightly compiler via `const fn`
  --> examples/i2c_haldriver_printmagserial.rs:31:62
   |
31 | static MAG3110: Mutex<RefCell<Option<Mag3110<I2c<TWI1>>>>> = Mutex::new(RefCell::new(None));
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is there any good workaround we can use here? Not being able to pass around peripherals and data safely into/out of interrupt handlers would be pretty bad, IMHO.

**Comment by TeXitoi** [comment]
In your Cargo.toml, you can just

```
bare-metal = { version = "0.2.4", features = ["const-fn"] }
```

It works on stable.

Maybe it should be the default now?

**Comment by adamgreig** [comment]
@therealprof we can close this now, right?
